### PR TITLE
Expose more of the keyring options

### LINKED ISSUE #12: Secrets backend choosing doesn't seem to work
On linux, attempting to specify a secret-backend other than kwallet (which isn't installed, because people tend to not use KDE here) fails:

```
# me on my-box in ~/mydir on git:master ✖︎ [10:04:40]
→ go run cmd/bk/main.go configure buildkite
──── Configuring Buildkite GraphQL credentials

Create a GraphQL token at https://buildkite.com/user/api-access-tokens/new. Make sure to tick the GraphQL scope at the bottom.

GraphQL Token: me@here.com ✅

�� The name org.kde.kwalletd was not provided by any .service files
exit status 1
[1]    2541 exit 1     go run cmd/bk/main.go configure buildkite

# me on my-box in ~/mydir on git:master ✖︎ [10:06:01]
→ go run cmd/bk/main.go configure buildkite --keyring-backend=secret-service
──── Configuring Buildkite GraphQL credentials

Create a GraphQL token at https://buildkite.com/user/api-access-tokens/new. Make sure to tick the GraphQL scope at the bottom.

GraphQL Token: me@here.com ✅

�� The name org.kde.kwalletd was not provided by any .service files
exit status 1
[1]    2918 exit 1     go run cmd/bk/main.go configure buildkite --keyring-backend=secret-service

# me on my-box in ~/mydir on git:master ✖︎ [10:06:44]
→ go run cmd/bk/main.go configure buildkite --keyring-backend=file          
──── Configuring Buildkite GraphQL credentials

Create a GraphQL token at https://buildkite.com/user/api-access-tokens/new. Make sure to tick the GraphQL scope at the bottom.

GraphQL Token: me@here.com ✅

�� The name org.kde.kwalletd was not provided by any .service files
exit status 1
[1]    3048 exit 1     go run cmd/bk/main.go configure buildkite --keyring-backend=file

# me on my-box in ~/mydir on git:master ✖︎ [10:07:04]
→ go run cmd/bk/main.go --keyring-backend=file configure backend
�� unexpected backend
exit status 1
[1]    3225 exit 1     go run cmd/bk/main.go --keyring-backend=file configure backend

# me on my-box in ~/mydir on git:master ✖︎ [10:07:09]
→ go run cmd/bk/main.go --keyring-backend=file configure buildkite
──── Configuring Buildkite GraphQL credentials

Create a GraphQL token at https://buildkite.com/user/api-access-tokens/new. Make sure to tick the GraphQL scope at the bottom.

GraphQL Token: me@here.com ✅

�� The name org.kde.kwalletd was not provided by any .service files
exit status 1
[1]    3378 exit 1     go run cmd/bk/main.go --keyring-backend=file configure buildkite
```

### LINKED ISSUE #16: No directory provided for file keyring
What is the proper option to get the initial install working?  The current docs result in the below error:

```
ubuntu@ip-10-221-102-20 ~ $ bk configure
──── Ok! Let's get started with configuring bk 🚀


──── Configuring Buildkite GraphQL credentials

Create a GraphQL token at https://buildkite.com/user/api-access-tokens/new. Make sure to tick the GraphQL scope at the bottom.

GraphQL Token: anthonyXXXXXion.com ✅

🚨 No directory provided for file keyring
```

Keyring-backend option mentions file but if I specify a file I get a confusing error:
```
22:24 $ bk configure --keyring-backend=$HOME/test
🚨 enum value must be one of file, got '/home/ubuntu/test'
```

### PR DESCRIPTION
**Pull request by lox**
This exposes configuration for setting the path to the `file` backend in keyring, as well as for `pass` and the keychain name for `keychain`. Closes #16.

This also removes `secret-service` and `kwallet` from the defaults. You can select them manually, but not by default. Closes #12.

### CODE REVIEW

File: cmd/bk/main.go [hunk 1]
```diff
@@ -63,8 +89,52 @@ func run(args []string, exit func(int)) {
...
+		if keyringBackend == `keyring` && keyringKeychain == `` {
+			keyringKeychain = `login`
+		}
+
 		keyringImpl, err = keyring.Open(keyring.Config{
-			ServiceName: "buildkite",
+			ServiceName:              "buildkite",
+			AllowedBackends:          allowedBackends,
+			KeychainName:             keyringKeychain,
+			FileDir:                  "~/.buildkite/keyring/",
```
Comment (petemounce) [inline cmd/bk/main.go]: Could that become `.config/buildkite/keyring` by default?

Complies with XDG directory specification.  https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
